# Makefile autogenerated by premake
# Don't edit this file! Instead edit `premake.lua` then rerun `make`
# Options:
#   CONFIG=[Debug|Release]

ifndef CONFIG
  CONFIG=Release
endif

export CONFIG

.PHONY: all clean KomodoDrop

all: KomodoDrop

Makefile: smugmug.lua
	@echo ==== Regenerating Makefiles ====
	@premake --file $^ --cc gcc --target gnu

KomodoDrop:
	@echo ==== Building KomodoDrop ====
	@$(MAKE) --no-print-directory -C . -f KomodoDrop.make

clean:
	@$(MAKE) --no-print-directory -C . -f KomodoDrop.make clean
